### ISSUE TITLE
Feature Functionality & Data Element Break Down

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#10]
# AssistU MVP & Application Process Flow

- New client registers on the web app entering Name, Email, Phone number, password, and phone number  (Login with google/facebook is also available)
- A registered Client can login with email- password. (Login with google/facebook is also available)
- After logging in, the Client selects a service from the list of services available on the home page.
- In the next step, the Client provides the service location address, date, with service start and end times.  All fields are required.  The number of service hours is calculated and provided for the Client.
- Payment summary of the order is displayed, and the Client confirms the payment method (only direct Client to Fixer cash payments in version 1.0)  
- In case, an unregistered Client selects to confirm booking service, the Client is prompted to login before the order process can conclude, and the payment summary displayed.
- A registered client can see the list of all orders.

## Component Sections & Features
- [x] Services  
- [x] LeaderShip
- [x] Contact Form
- [x] Mission
- [x] Header
- [x] Footer
- [x] Booking Services
- [x] Payment Summary
- [x] Order Confirmation
- [x] Order History
- [x] User Authentication

**Comment by vai1205** [comment]
@CodeMeKathy, added user story for landing and contact us form.
