### ISSUE TITLE
Confirm App Logo

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#12]
# Current Options 

![image.png](https://images.zenhubusercontent.com/5d18f7fbd481de268023d5a8/f849b4e5-25f4-4110-9bcf-69ffa503071e)
![image.png](https://images.zenhubusercontent.com/5d18f7fbd481de268023d5a8/c8c9273e-27ca-49ef-9d7a-589a031eb2a9)
![image.png](https://images.zenhubusercontent.com/5d18f7fbd481de268023d5a8/e09c11e3-ddb8-471a-af8a-4630c681926b)

**Comment by vai1205** [comment]
![assistU logo](https://user-images.githubusercontent.com/50205141/61587598-c9cdab80-abaa-11e9-9ae5-6206f3a57632.png)
I am happy with this one @CodeMeKathy
