### ISSUE TITLE
Create Header Component

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#15]
### User Story 

- Any user should be able to click on the header and be taken to the home landing page.
- Any user should be able to click `Sign In or Sign Up` and be taken to the sign-up and sign-in page

### Current Draft Mockup or Inspiration
![Header Mockup 1](https://user-images.githubusercontent.com/32943879/61598666-22bf3300-abef-11e9-8436-9506f31b3531.png)
![Header Mockup 2](https://user-images.githubusercontent.com/32943879/61598667-2357c980-abef-11e9-9e10-fcf9f3e966f3.png)

### Future Releases

**Comment by vai1205** [comment]
@CodeMeKathy, confirmed header matches mockup.
