### ISSUE TITLE
Create Footer Component

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#17]
### Current Draft Mockup or Inspiration
![Footer Mockup](https://user-images.githubusercontent.com/32943879/63037328-ea78e080-be8c-11e9-9d1d-8805bc87c598.png)
![Mobile Footer Mockup](https://user-images.githubusercontent.com/32943879/63037206-9a018300-be8c-11e9-9fb4-739fc8bc11a5.png)

### Component Data Elements
- NA
### Component MVP Requirements 
 - [x] Match Mockup deisgn

### Component Future Releases
 - [ ] Any user should be able to select Social Icons and be redirected on a new tab to AssistU accounts.

**Comment by vai1205** [comment]
Footer component created. Please review and close the issue @CodeMeKathy 

### Desktop View
![Screen Shot 2019-08-14 at 2 13 17 PM](https://user-images.githubusercontent.com/50205141/63007171-c1ad1700-be9d-11e9-9246-f887d5a1a3d0.png)

### Mobile View
![Screen Shot 2019-08-14 at 2 35 31 PM](https://user-images.githubusercontent.com/50205141/63008761-dd65ec80-bea0-11e9-92ed-33e35665ae7f.png)
