### ISSUE TITLE
Setup Contact Form Functionality

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#21]
## Component User Features & Stories

- [x] Any user should be able to fill out the contact form and send the message pressing submit button
- [x] Any used should not be able to leave the contact form blank.
- [x] Any user should be redirected to a thank-you page after filling up the form and pressing submit button.

### Current Draft Mockup or Inspiration
![Contact Form Mockup](https://user-images.githubusercontent.com/32943879/61598055-04a10500-abe6-11e9-8f6f-990612bd3a38.png)

### Component Data Elements
- Contact Email
- Contact Subject
- Contact Message

### Component MVP Requirements
- [x] Form Data Submission Functionality
- [x] Match mockup design 

### **Component Future** Releases

**Comment by vai1205** [comment]
@CodeMeKathy Updated features listing

**Comment by vai1205** [comment]
@CodeMeKathy updated component data elements.
