### ISSUE TITLE
Finalize font-style(s) for the app

### ISSUE THREAD

**Issue by vai1205** [chingu-voyages/v10-geckos-team-14#22]
Please select a font-style for the app:-
Suggestions:
For headings
1. https://fonts.google.com/specimen/Chewy
2. https://fonts.google.com/specimen/Concert+One
3. https://fonts.google.com/specimen/Fredoka+One
4. https://fonts.google.com/specimen/Londrina+Solid
For paragraphs:
1. https://fonts.google.com/specimen/Roboto
2. https://fonts.google.com/specimen/Oxygen
3. https://fonts.google.com/specimen/Domine
4. https://fonts.google.com/specimen/Rambla

**Comment by CodeMeKathy** [comment]
@vai1205 Confirmed font selections per our conversation.  See below.

## Confirmed Fonts
Heading: [Fredoka One](https://fonts.google.com/specimen/Fredoka+One)
Paragraph: [Domine](https://fonts.google.com/specimen/Domine)
