### ISSUE TITLE
Create Contact Form Successful Submission Alert

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#28]
### User Story 

- Any user, when fills the contact form, should be notified about the successful submission of the form.

### Component Data Elements
- NA

### Component MVP Requirements
- [x] Match mockup design

### Future Releases
- Show modal/alert on the same page rather than rendering a new view.

**Comment by vai1205** [comment]
A new 'view' has been created, that will be rendered on the successful submission of contact form by the users. Please review @CodeMeKathy.
![Screen Shot 2019-08-14 at 1 44 18 PM](https://user-images.githubusercontent.com/50205141/63005473-4433d780-be9a-11e9-90f5-3dd93f83b272.png)

**Comment by CodeMeKathy** [comment]
@vai1205 - Thank you! Looks great.  Please note, I updated the placeholder text.
