### ISSUE TITLE
Add iPad Footer Media Query

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#32]
## Component User Features & Stories

- Users have an eye-pleasing experience looking to the footer on iPad/tablets. 

### Component Data Elements
- NA

### Component MVP Requirements
- [x] Check on iPad/iPad Pro
- [x] Match mockup design 

### **Component Future** Releases
- NA

**Comment by vai1205** [comment]
Updated the footer icons and added media queries for the iPad. Please review and close the issue @CodeMeKathy 

### iPad vertical screen orientation
![Screen Shot 2019-08-14 at 2 05 56 PM](https://user-images.githubusercontent.com/50205141/63006732-ccb37780-be9c-11e9-84e3-a3f1e2808293.png)

### iPad horizontal screen orientation
![Screen Shot 2019-08-14 at 2 05 43 PM](https://user-images.githubusercontent.com/50205141/63006771-eeacfa00-be9c-11e9-9537-efa9ef249aa6.png)

### iPad Pro vertical screen orientation
![Screen Shot 2019-08-14 at 2 05 28 PM](https://user-images.githubusercontent.com/50205141/63006804-01273380-be9d-11e9-93d3-7af8e6502133.png)

### iPad horizontal screen orientation
![Screen Shot 2019-08-14 at 2 06 06 PM](https://user-images.githubusercontent.com/50205141/63006825-100de600-be9d-11e9-9e16-f66f519354e7.png)
