### ISSUE TITLE
Draft Landing Page LeaderShip Section Bio Statements

### ISSUE THREAD

**Issue by vai1205** [chingu-voyages/v10-geckos-team-14#41]
- [x] @CodeMeKathy please update your personal bio
- [x] @vai1205  please update your personal bio

**Comment by CodeMeKathy** [comment]
@vai1205 - I added my bio to the home page LeaderShip section and pushed it to the master branch.  See added text below, for convenience.

#### Kathy Lambert is an intellectually curious individual with an insatiable desire to understand. She utilizes her diverse background, experiences, and skills to help be a resourceful, organized and forward-thinking project manager, web designer, and software developer.  Passionate about creating applications which are tools of efficiency in people's lives.  Giving time back for what matter's most in life.

**Comment by vai1205** [comment]
@CodeMeKathy I have added my Bio and have pushed it to the `finalFixesVai` branch. Please review the text below and close the issue.
Vaibhav Srivastava is a self-taught full-stack web developer passionate about building appealing, high-performance and easy-to-use applications on top of cutting-edge tech stacks. Embracing self-learning, he loves to adopt new tech stacks and bring the most productive outcome with it. He has a strong belief that codes and automation actually aim to solve real-world problems in the most efficient manner.
