### ISSUE TITLE
Define MVP

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#5]
#MVP Reminders
 - [ ] Create a simple, concise statement of what your application will achieve and the value it has to its users. This is your North Star. Every function and feature in the application should reinforce this goal.
 - [ ] Listing the functions you want to include in the application. Prioritize them by identifying which are needs and which are wants. 
 - [ ] Listing the features in each function and prioritize them in the same manner. Identify which are needs and which are wants.
 - [ ] Define attributes and roles of your end-users and match them to your features and functions. This helps ensure that the app will have a logical flow, and more importantly, that it meets all user needs.
 - [ ] Adding the tasks needed to reach MVP status to your project backlog. Since you'll be following Agile principles, the backlog won't be complete until the latter part of the project. The team will continuously revise it in each sprint.
 - [ ] Pleasant user experience
 - [ ] Clean and pleasant UI / layout
 - [ ] Handling of edge cases, so your app doesn't crash when users use it
 - [ ] Confirm deployed methods
 - [ ] Responsive design so users can use on mobile and web

**Comment by vai1205** [comment]
MVP features:

Party | Role | Product
-- | -- | --
Client | Customer who can order for workers. | Web App
Admin | Governing Company or organisation | Web based Admin Panel ( To be Developed in later version )

Process flow:

* New client registers on the web app entering Name, Email, Phone number, password, and phone number  (Login with google/facebook is also available)
* Registered client can login with email- password. (Login with google/facebook is also available)
* After logging in, Client selects a service from the list of services available on the home page.
* In the next step selects the time/date when service is required. Along with this also enters the 
 number of hours for which service is required and is billed accordingly.
* Next step, client enters the Address string where the service is required.
 Summary of order is displayed 
* Client selects payment method (only Cash on delivery for version 1.0)  
* In case, an unregistered client selects the service, date/time etc. then he/she is prompted to login 
  before order summary Is displayed.
* In case of any query, client can ask to customer care filling a form with details 
  Registered client can see the list of orders booked so far.

**Comment by CodeMeKathy** [comment]
@vai1205 - I finalized MVP Users, Requirements and Process Flow details.
