### ISSUE TITLE
Create Application Data Schema

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#7]
@vai1205 - [ ] Please update issue to include the original app ERD.  Thank you in advance!

**Comment by vai1205** [comment]
@CodeMeKathy DB Schema is shown in the file below. Please review and close the issue.
![assistU DB Structure](https://user-images.githubusercontent.com/50205141/63103867-898bfe00-bf9b-11e9-979a-b716f67d262a.png)
