### ISSUE TITLE
Confirm App Color Palette

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#8]
# Confirm App Color Palette

## Current Option
- Background | Gainsboro (Soft Pink): #E5D8D9
- Primary | Tyrian Purple (Blood Red Wine): #63032E
- Secondary Colors | Orange-Yellow: #F9D276
- [Palette Generator](https://coolors.co/e5d8d9-63032e-f9d276-8d5a97-907f9f)
*Note: Lock first three (3) colors before pressing the space bar to generate two new alternative colors
![Current Color Palette Option](https://user-images.githubusercontent.com/32943879/61502337-95d36a00-a9a1-11e9-8d45-9ef2cd6659cf.png)

**Comment by vai1205** [comment]
@CodeMeKathy this is what we have discussed together to come up with. 
https://coolors.co/f1f7f0-63032e-f9d276-8d5a97-e1e3f0

**Comment by vai1205** [comment]
![color-pallate](https://user-images.githubusercontent.com/50205141/61593279-2bb60180-abfb-11e9-9e61-22173a52a622.png)
