### ISSUE TITLE
Update Repo License & Metadata 

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#9]
## MIT License
To complete the below section of the MIT License. 
MIT. Copyright (c) `[]() and []()`.
Example: [Kathy Lambert](https://kathylambert.me) Format: `[Name](Website of Choice)`

## Metadata

Examples: 
  `<meta name="author" content="Author Personal Portfolio" href="https://kathylambert.me">`
 ` <meta name="author" content="Author GitHub Portfolio" href="https://github.com/CodeMeKathy">`

Format: 
` <meta name="author" content="Author Personal Portfolio" href="#">`
 ` <meta name="author" content="Author GitHub Portfolio" href="#">`

**Comment by CodeMeKathy** [comment]
# Assigned Task
- [ ] @vai1205, please provide the issue requested information about yourself. Thank you in advance!

**Comment by vai1205** [comment]
This is my information as of now. Will update some in coming future.

<meta name="Vaibhav Srivastava" content="Author Email" href="mailto:vaibhav.12may95@gmail.com?Subject=Got%20you%20from%AssistU%20Web%20App">
<meta name="Vaibhav Srivastava" content="Author GitHub Portfolio" href="https://github.com/vai1205">

**Comment by vai1205** [comment]
Repo Licence information code:
```html
<footer>
  <div class="footer text-center">&copy; Copyright 2019
    <a herf="https://github.com/chingu-voyages/v10-geckos-team-14">ChinguV10 Team#14
    </a>
    <br /> Made with ❤️, Lots of ☕️ & Chingu 
  </div>
</footer>

**Comment by vai1205** [comment]
Done adding the metadata for you and I, and also added license information to the code and have pushed it to **landingPage** branch.

**Comment by vai1205** [comment]
@CodeMeKathy  Please pull it and review the changes.  Thanks!

**Comment by CodeMeKathy** [comment]
@vai1205, thank you for your changes.  Changes updated and finalized the metadata social media additions to the master branch.
